image: mcr.microsoft.com/dotnet/sdk:9.0

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: atlassian/default-image:4
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:fmisrl/password-changer.git
          - cd password-changer.git
          - git push --mirror git@github.com:fmisrl/password-changer.git
    - step:
        name: Build
        runs-on:
          - self.hosted
          - windows
        script:
          - Get-ChildItem .\PasswordChanger.Web\wwwroot\lib\jquery-validation-unobtrusive\ -Recurse
          - dotnet tool install --global wix --version 5.0.2
          - dotnet publish PasswordChanger.Web/PasswordChanger.Web.csproj --configuration Release -v diag
          - tree /f
          - tree $env:USERPROFILE
          - dotnet build PasswordChanger.Installer/PasswordChanger.Installer.csproj
          - Get-ChildItem  -Recurse -Filter "jquery.validate.unobtrusive.js"
