image: mcr.microsoft.com/dotnet/sdk:9.0

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: Build .NET Web
        script:
          - dotnet build PasswordChanger.Web/PasswordChanger.Web.csproj --configuration Release
    - step:
        name: Build MSI (WiX)
        image: docker:20.10.16
        script:
          - apk update && apk install -y wine zip
          - wget https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
          - unzip wix311-binaries.zip
          - wine candle.exe $(pwd)/PasswordChanger.Installer/PasswordChanger.wxs
          - wine light.exe $(pwd)/PasswordChanger.Installer/PasswordChanger.wixobj -out $(pwd)/PasswordChanger.Installer/PasswordChanger.msi -sval
        artifacts:
          - PasswordChanger.Installer/PasswordChanger.msi
    - step:
        name: Sync GitHub Mirror
        image: atlassian/default-image:4
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:fmisrl/password-changer.git
          - cd password-changer.git
          - git push --mirror git@github.com:fmisrl/password-changer.git
