image: mcr.microsoft.com/dotnet/sdk:9.0

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: atlassian/default-image:4
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:fmisrl/password-changer.git
          - cd password-changer.git
          - git push --mirror git@github.com:fmisrl/password-changer.git
    - step:
        name: Build
        runs-on:
          - self.hosted
          - windows
        caches:
          - dotnetcore
        script:
          - Get-ChildItem  -Recurse -Filter "jquery.validate.unobtrusive.js"
          - dotnet restore PasswordChanger.Web/PasswordChanger.Web.csproj
          - tree /f
          - Get-ChildItem  -Recurse -Filter "jquery.validate.unobtrusive.js"
          - dotnet publish PasswordChanger.Web/PasswordChanger.Web.csproj --configuration Release
          - tree /f
          - Get-ChildItem  -Recurse -Filter "jquery.validate.unobtrusive.js"
          - dotnet build PasswordChanger.Installer/PasswordChanger.Installer.csproj --configuration Release
          - Get-ChildItem  -Recurse -Filter "jquery.validate.unobtrusive.js"
