image: mcr.microsoft.com/dotnet/sdk:9.0

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: Build .NET Web
        script:
          - dotnet build PasswordChanger.Web/PasswordChanger.Web.csproj --configuration Release
    - step:
        name: Build MSI (WiX)
        image: docker:20.10.16
        script:
          - apk update && apk add wine zip wget bash # Install bash
          - wget https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
          - chmod +x dotnet-install.sh
          - bash ./dotnet-install.sh -c 9.0 # Use bash to run the script.
          - export PATH="$PATH:$HOME/.dotnet"
          - dotnet tool install --global wix --version 5.0.2
          - export PATH="$PATH:$HOME/.dotnet/tools"
          - wine candle.exe $(pwd)/PasswordChanger.Installer/PasswordChanger.wxs
          - wine light.exe $(pwd)/PasswordChanger.Installer/PasswordChanger.wixobj -out $(pwd)/PasswordChanger.Installer/PasswordChanger.msi -sval
        artifacts:
          - PasswordChanger.Installer/PasswordChanger.msi
    - step:
        name: Sync GitHub Mirror
        image: atlassian/default-image:4
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:fmisrl/password-changer.git
          - cd password-changer.git
          - git push --mirror git@github.com:fmisrl/password-changer.git
