image: mcr.microsoft.com/dotnet/sdk:9.0

clone:
  lfs: true

pipelines:
  default:
    - step:
          name: Sync GitHub Mirror
          image: atlassian/default-image:4
          clone:
            enabled: false
          script:
            - git clone --bare git@bitbucket.org:fmisrl/password-changer.git
            - cd password-changer.git
            - git push --mirror git@github.com:fmisrl/password-changer.git
    - step:
        name: Build .NET Web
        script:
          - dotnet build PasswordChanger.Web/PasswordChanger.Web.csproj --configuration Release
    - step:
        name: Build MSI (WiX)
        image: felfert/wix:latest
        services:
          - docker
        script:
          - docker run --rm felfert/wix mkhostwrappers | sh
          - cd PasswordChanger.Installer
          - candle PasswordChangerInstaller.wxs
          - light -sval PasswordChangerInstaller.wixobj -o PasswordChangerInstaller.msi
        artifacts:
          - PasswordChanger.Installer/PasswordChanger.msi
