image: mcr.microsoft.com/dotnet/sdk:9.0

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: atlassian/default-image:4
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:fmisrl/password-changer.git
          - cd password-changer.git
          - git push --mirror git@github.com:fmisrl/password-changer.git
    - step:
        name: Build
        runs-on:
          - self.hosted
          - windows
        script:
          - dotnet tool install --global wix --version 5.0.2

          - icacls "./" /q /c /t /grant Users:F
          - dotnet restore
          - dotnet publish PasswordChanger.Web/PasswordChanger.Web.csproj --no-restore
          - dotnet build PasswordChanger.Installer/PasswordChanger.Installer.csproj --no-restore
        artifacts:
          - out\**
