image: mcr.microsoft.com/dotnet/sdk:9.0

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: atlassian/default-image:4
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:fmisrl/password-changer.git
          - cd password-changer.git
          - git push --mirror git@github.com:fmisrl/password-changer.git
    - step:
        name: Build
        runs-on:
          - self.hosted
          - windows
        script:
          - tree $env:USERPROFILE
          - dotnet tool install --global wix --version 5.0.2
          - tree $env:USERPROFILE
          - dotnet restore PasswordChanger.Web/PasswordChanger.Web.csproj
          - dotnet publish PasswordChanger.Web/PasswordChanger.Web.csproj
          - tree $env:USERPROFILE
          - dotnet restore PasswordChanger.Installer/PasswordChanger.Installer.csproj
          - $wixPath = Join-Path $env:USERPROFILE ".nuget\packages\wixtoolset.sdk\5.0.2\tools\net6.0\wix.dll"
          - $wixExtPath = Join-Path $env:USERPROFILE ".nuget/packages/wixtoolset.ui.wixext/5.0.2/wixext5/WixToolset.UI.wixext.dll"
          - wix build PasswordChanger.Installer\PasswordChangerInstaller.wxs -o out\PasswordChangerInstaller.msi -ext $wixExtPath
          - tree /f
        artifacts:
          - out\**
