image: mcr.microsoft.com/dotnet/sdk:9.0

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: Build
        runs-on:
          - self-hosted
          - windows
        caches:
          - dotnetcore
        script:
          - dotnet build PasswordChanger.sln
    - step:
        name: Sync GitHub Mirror
        image: atlassian/default-image:4
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:fmisrl/password-changer.git
          - cd password-changer.git
          - git push --mirror git@github.com:fmisrl/password-changer.git
