image: mcr.microsoft.com/dotnet/sdk:9.0

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: Build .NET Web
        script:
          - dotnet build PasswordChanger.Web/PasswordChanger.Web.csproj --configuration Release
    - step:
        name: Build MSI (WiX)
        image: felfert/wix:latest
        services:
          - docker
        script:
          - docker run --rm felfert/wix mkhostwrappers | sh
          - cd PasswordChanger.Installer
          - find / -name WixToolset.UI.wixext
          - candle PasswordChangerInstaller.wxs -ext WixToolset.UI.wixext
          - light PasswordChangerInstaller.wixobj -o PasswordChangerInstaller.msi -ext WixToolset.UI.wixext
        artifacts:
          - PasswordChanger.Installer/PasswordChanger.msi
    - step:
        name: Sync GitHub Mirror
        image: atlassian/default-image:4
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:fmisrl/password-changer.git
          - cd password-changer.git
          - git push --mirror git@github.com:fmisrl/password-changer.git
