image: mcr.microsoft.com/dotnet/sdk:9.0

pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: atlassian/default-image:4
        script:
          - git push --mirror git@github.com:fmisrl/password-changer.git
