image: mcr.microsoft.com/dotnet/sdk:9.0

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: atlassian/default-image:4
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:fmisrl/password-changer.git
          - cd password-changer.git
          - git push --mirror git@github.com:fmisrl/password-changer.git
    - step:
        name: Build
        runs-on:
          - self.hosted
          - windows
        script:
          - dotnet tool install --global wix --version 5.0.2
          - dotnet restore
          - dotnet publish PasswordChanger.Web/PasswordChanger.Web.csproj
          - tree /f
          - Get-ChildItem .\PasswordChanger.Web\bin\Release\net9.0-windows\win-x64\publish\wwwroot\lib\jquery-validation-unobtrusive\ -Recurse
          - echo Publish
          - Get-Item -Force -Path ".\PasswordChanger.Web\bin\Release\net9.0-windows\win-x64\publish\wwwroot\lib\jquery-validation-unobtrusive\dist\jquery.validate.unobtrusive.js" | Format-List *
          - Get-Item -Force -Path ".\PasswordChanger.Web\bin\Release\net9.0-windows\win-x64\publish\wwwroot\lib\jquery-validation\dist\jquery.validate.js" | Format-List *
          - tree /f
          - echo Wwwroot
          - Get-Item -Force -Path ".\PasswordChanger.Web\wwwroot\lib\jquery-validation-unobtrusive\dist\jquery.validate.unobtrusive.js" | Format-List *
          - Get-Item -Force -Path ".\PasswordChanger.Web\wwwroot\lib\jquery-validation\dist\jquery.validate.js" | Format-List *
          - tree $env:USERPROFILE
          - dotnet build PasswordChanger.Installer/PasswordChanger.Installer.csproj
          - Get-ChildItem  -Recurse -Filter "jquery.validate.unobtrusive.js"
