image: mcr.microsoft.com/dotnet/sdk:9.0

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: Build .NET Web
        script:
          - dotnet build PasswordChanger.Web/PasswordChanger.Web.csproj --configuration Release --no-restore
    - step:
        name: Build MSI (WiX)
        image: dactiv/wix
        script:
          - docker run --rm -v $(pwd)/PasswordChanger.Installer:/wix dactiv/wix wine candle.exe /wix/PasswordChanger.wxs
          - docker run --rm -v $(pwd)/PasswordChanger.Installer:/wix dactiv/wix wine light.exe /wix/PasswordChanger.wixobj -out /wix/PasswordChanger.msi -sval
        artifacts:
          - PasswordChanger.Installer/PasswordChanger.msi
    - step:
        name: Sync GitHub Mirror
        image: atlassian/default-image:4
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:fmisrl/password-changer.git
          - cd password-changer.git
          - git push --mirror git@github.com:fmisrl/password-changer.git
